"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.multi_user_issue_custom_field_all_of import MultiUserIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.user import User
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['MultiUserIssueCustomFieldAllOf'] = MultiUserIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['User'] = User
from youtrack_api.model.multi_user_issue_custom_field import MultiUserIssueCustomField


class TestMultiUserIssueCustomField(unittest.TestCase):
    """MultiUserIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiUserIssueCustomField(self):
        """Test MultiUserIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiUserIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
