"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.project_color import ProjectColor
globals()['ProjectColor'] = ProjectColor
from youtrack_api.model.project_based_color_coding_all_of import ProjectBasedColorCodingAllOf


class TestProjectBasedColorCodingAllOf(unittest.TestCase):
    """ProjectBasedColorCodingAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectBasedColorCodingAllOf(self):
        """Test ProjectBasedColorCodingAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectBasedColorCodingAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
