"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.base_bundle import BaseBundle
from youtrack_api.model.enum_bundle_all_of import EnumBundleAllOf
from youtrack_api.model.enum_bundle_element import EnumBundleElement
globals()['BaseBundle'] = BaseBundle
globals()['EnumBundleAllOf'] = EnumBundleAllOf
globals()['EnumBundleElement'] = EnumBundleElement
from youtrack_api.model.enum_bundle import EnumBundle


class TestEnumBundle(unittest.TestCase):
    """EnumBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnumBundle(self):
        """Test EnumBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnumBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
