"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.activity_item import ActivityItem
from youtrack_api.model.custom_field_activity_item_all_of import CustomFieldActivityItemAllOf
from youtrack_api.model.issue import Issue
from youtrack_api.model.text_custom_field_activity_item import TextCustomFieldActivityItem
globals()['ActivityItem'] = ActivityItem
globals()['CustomFieldActivityItemAllOf'] = CustomFieldActivityItemAllOf
globals()['Issue'] = Issue
globals()['TextCustomFieldActivityItem'] = TextCustomFieldActivityItem
from youtrack_api.model.custom_field_activity_item import CustomFieldActivityItem


class TestCustomFieldActivityItem(unittest.TestCase):
    """CustomFieldActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomFieldActivityItem(self):
        """Test CustomFieldActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomFieldActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
