"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.custom_field_defaults import CustomFieldDefaults
from youtrack_api.model.field_type import FieldType
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['CustomFieldDefaults'] = CustomFieldDefaults
globals()['FieldType'] = FieldType
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.custom_field import CustomField


class TestCustomField(unittest.TestCase):
    """CustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomField(self):
        """Test CustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
