"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.base_bundle import BaseBundle
from youtrack_api.model.state_bundle_all_of import StateBundleAllOf
from youtrack_api.model.state_bundle_element import StateBundleElement
globals()['BaseBundle'] = BaseBundle
globals()['StateBundleAllOf'] = StateBundleAllOf
globals()['StateBundleElement'] = StateBundleElement
from youtrack_api.model.state_bundle import StateBundle


class TestStateBundle(unittest.TestCase):
    """StateBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateBundle(self):
        """Test StateBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
