"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.comment_attachments_activity_item_all_of import CommentAttachmentsActivityItemAllOf
from youtrack_api.model.issue_attachment import IssueAttachment
from youtrack_api.model.issue_comment import IssueComment
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
globals()['CommentAttachmentsActivityItemAllOf'] = CommentAttachmentsActivityItemAllOf
globals()['IssueAttachment'] = IssueAttachment
globals()['IssueComment'] = IssueComment
globals()['MultiValueActivityItem'] = MultiValueActivityItem
from youtrack_api.model.comment_attachments_activity_item import CommentAttachmentsActivityItem


class TestCommentAttachmentsActivityItem(unittest.TestCase):
    """CommentAttachmentsActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentAttachmentsActivityItem(self):
        """Test CommentAttachmentsActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommentAttachmentsActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
