"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue import Issue
from youtrack_api.model.issue_attachment import IssueAttachment
from youtrack_api.model.user import User
from youtrack_api.model.visibility import Visibility
globals()['Issue'] = Issue
globals()['IssueAttachment'] = IssueAttachment
globals()['User'] = User
globals()['Visibility'] = Visibility
from youtrack_api.model.issue_comment import IssueComment


class TestIssueComment(unittest.TestCase):
    """IssueComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueComment(self):
        """Test IssueComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
