"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle_custom_field_defaults import BundleCustomFieldDefaults
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.version_bundle import VersionBundle
from youtrack_api.model.version_bundle_custom_field_defaults_all_of import VersionBundleCustomFieldDefaultsAllOf
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['BundleCustomFieldDefaults'] = BundleCustomFieldDefaults
globals()['CustomField'] = CustomField
globals()['VersionBundle'] = VersionBundle
globals()['VersionBundleCustomFieldDefaultsAllOf'] = VersionBundleCustomFieldDefaultsAllOf
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.version_bundle_custom_field_defaults import VersionBundleCustomFieldDefaults


class TestVersionBundleCustomFieldDefaults(unittest.TestCase):
    """VersionBundleCustomFieldDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionBundleCustomFieldDefaults(self):
        """Test VersionBundleCustomFieldDefaults"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionBundleCustomFieldDefaults()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
