"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.enum_bundle_element import EnumBundleElement
from youtrack_api.model.multi_enum_issue_custom_field_all_of import MultiEnumIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['EnumBundleElement'] = EnumBundleElement
globals()['MultiEnumIssueCustomFieldAllOf'] = MultiEnumIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.multi_enum_issue_custom_field import MultiEnumIssueCustomField


class TestMultiEnumIssueCustomField(unittest.TestCase):
    """MultiEnumIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiEnumIssueCustomField(self):
        """Test MultiEnumIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiEnumIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
