"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.state_bundle_element import StateBundleElement
from youtrack_api.model.state_issue_custom_field_all_of import StateIssueCustomFieldAllOf
globals()['DatabaseSingleValueIssueCustomField'] = DatabaseSingleValueIssueCustomField
globals()['ProjectCustomField'] = ProjectCustomField
globals()['StateBundleElement'] = StateBundleElement
globals()['StateIssueCustomFieldAllOf'] = StateIssueCustomFieldAllOf
from youtrack_api.model.state_issue_custom_field import StateIssueCustomField


class TestStateIssueCustomField(unittest.TestCase):
    """StateIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateIssueCustomField(self):
        """Test StateIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
