"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_project_custom_field import BuildProjectCustomField
from youtrack_api.model.bundle_project_custom_field import BundleProjectCustomField
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.enum_project_custom_field import EnumProjectCustomField
from youtrack_api.model.group_project_custom_field import GroupProjectCustomField
from youtrack_api.model.owned_project_custom_field import OwnedProjectCustomField
from youtrack_api.model.period_project_custom_field import PeriodProjectCustomField
from youtrack_api.model.project import Project
from youtrack_api.model.simple_project_custom_field import SimpleProjectCustomField
from youtrack_api.model.state_project_custom_field import StateProjectCustomField
from youtrack_api.model.text_project_custom_field import TextProjectCustomField
from youtrack_api.model.user_project_custom_field import UserProjectCustomField
from youtrack_api.model.version_project_custom_field import VersionProjectCustomField
globals()['BuildProjectCustomField'] = BuildProjectCustomField
globals()['BundleProjectCustomField'] = BundleProjectCustomField
globals()['CustomField'] = CustomField
globals()['EnumProjectCustomField'] = EnumProjectCustomField
globals()['GroupProjectCustomField'] = GroupProjectCustomField
globals()['OwnedProjectCustomField'] = OwnedProjectCustomField
globals()['PeriodProjectCustomField'] = PeriodProjectCustomField
globals()['Project'] = Project
globals()['SimpleProjectCustomField'] = SimpleProjectCustomField
globals()['StateProjectCustomField'] = StateProjectCustomField
globals()['TextProjectCustomField'] = TextProjectCustomField
globals()['UserProjectCustomField'] = UserProjectCustomField
globals()['VersionProjectCustomField'] = VersionProjectCustomField
from youtrack_api.model.project_custom_field import ProjectCustomField


class TestProjectCustomField(unittest.TestCase):
    """ProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectCustomField(self):
        """Test ProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
