"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue import Issue
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
from youtrack_api.model.user import User
from youtrack_api.model.voters_activity_item_all_of import VotersActivityItemAllOf
globals()['Issue'] = Issue
globals()['MultiValueActivityItem'] = MultiValueActivityItem
globals()['User'] = User
globals()['VotersActivityItemAllOf'] = VotersActivityItemAllOf
from youtrack_api.model.voters_activity_item import VotersActivityItem


class TestVotersActivityItem(unittest.TestCase):
    """VotersActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVotersActivityItem(self):
        """Test VotersActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VotersActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
