"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.state_bundle_element_all_of import StateBundleElementAllOf


class TestStateBundleElementAllOf(unittest.TestCase):
    """StateBundleElementAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateBundleElementAllOf(self):
        """Test StateBundleElementAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateBundleElementAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
