"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_work_item import IssueWorkItem
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
from youtrack_api.model.work_item_type import WorkItemType
from youtrack_api.model.work_item_type_activity_item_all_of import WorkItemTypeActivityItemAllOf
globals()['IssueWorkItem'] = IssueWorkItem
globals()['MultiValueActivityItem'] = MultiValueActivityItem
globals()['WorkItemType'] = WorkItemType
globals()['WorkItemTypeActivityItemAllOf'] = WorkItemTypeActivityItemAllOf
from youtrack_api.model.work_item_type_activity_item import WorkItemTypeActivityItem


class TestWorkItemTypeActivityItem(unittest.TestCase):
    """WorkItemTypeActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkItemTypeActivityItem(self):
        """Test WorkItemTypeActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkItemTypeActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
