"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.uses_markup_activity_item_all_of import UsesMarkupActivityItemAllOf


class TestUsesMarkupActivityItemAllOf(unittest.TestCase):
    """UsesMarkupActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsesMarkupActivityItemAllOf(self):
        """Test UsesMarkupActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UsesMarkupActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
