"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_folder import IssueFolder
from youtrack_api.model.issue_tag import IssueTag
from youtrack_api.model.saved_query import SavedQuery
from youtrack_api.model.user import User
from youtrack_api.model.user_group import UserGroup
from youtrack_api.model.watch_folder_all_of import WatchFolderAllOf
globals()['IssueFolder'] = IssueFolder
globals()['IssueTag'] = IssueTag
globals()['SavedQuery'] = SavedQuery
globals()['User'] = User
globals()['UserGroup'] = UserGroup
globals()['WatchFolderAllOf'] = WatchFolderAllOf
from youtrack_api.model.watch_folder import WatchFolder


class TestWatchFolder(unittest.TestCase):
    """WatchFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWatchFolder(self):
        """Test WatchFolder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WatchFolder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
