"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.version_bundle_element_all_of import VersionBundleElementAllOf


class TestVersionBundleElementAllOf(unittest.TestCase):
    """VersionBundleElementAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionBundleElementAllOf(self):
        """Test VersionBundleElementAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionBundleElementAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
