"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.activity_item import ActivityItem
from youtrack_api.model.attachment_activity_item import AttachmentActivityItem
from youtrack_api.model.comment_activity_item import CommentActivityItem
from youtrack_api.model.issue_created_activity_item import IssueCreatedActivityItem
from youtrack_api.model.vcs_change_activity_item import VcsChangeActivityItem
from youtrack_api.model.work_item_activity_item import WorkItemActivityItem
globals()['ActivityItem'] = ActivityItem
globals()['AttachmentActivityItem'] = AttachmentActivityItem
globals()['CommentActivityItem'] = CommentActivityItem
globals()['IssueCreatedActivityItem'] = IssueCreatedActivityItem
globals()['VcsChangeActivityItem'] = VcsChangeActivityItem
globals()['WorkItemActivityItem'] = WorkItemActivityItem
from youtrack_api.model.created_deleted_activity_item import CreatedDeletedActivityItem


class TestCreatedDeletedActivityItem(unittest.TestCase):
    """CreatedDeletedActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatedDeletedActivityItem(self):
        """Test CreatedDeletedActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreatedDeletedActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
