"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue import Issue
from youtrack_api.model.sprint import Sprint
globals()['Issue'] = Issue
globals()['Sprint'] = Sprint
from youtrack_api.model.sprint_activity_item_all_of import SprintActivityItemAllOf


class TestSprintActivityItemAllOf(unittest.TestCase):
    """SprintActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprintActivityItemAllOf(self):
        """Test SprintActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprintActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
