"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.version_bundle import VersionBundle
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['VersionBundle'] = VersionBundle
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.version_bundle_custom_field_defaults_all_of import VersionBundleCustomFieldDefaultsAllOf


class TestVersionBundleCustomFieldDefaultsAllOf(unittest.TestCase):
    """VersionBundleCustomFieldDefaultsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionBundleCustomFieldDefaultsAllOf(self):
        """Test VersionBundleCustomFieldDefaultsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionBundleCustomFieldDefaultsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
