"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue import Issue
from youtrack_api.model.issue_tag import IssueTag
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
from youtrack_api.model.tags_activity_item_all_of import TagsActivityItemAllOf
globals()['Issue'] = Issue
globals()['IssueTag'] = IssueTag
globals()['MultiValueActivityItem'] = MultiValueActivityItem
globals()['TagsActivityItemAllOf'] = TagsActivityItemAllOf
from youtrack_api.model.tags_activity_item import TagsActivityItem


class TestTagsActivityItem(unittest.TestCase):
    """TagsActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagsActivityItem(self):
        """Test TagsActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagsActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
