"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle_project_custom_field import BundleProjectCustomField
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.owned_bundle import OwnedBundle
from youtrack_api.model.owned_bundle_custom_field_defaults_all_of import OwnedBundleCustomFieldDefaultsAllOf
from youtrack_api.model.owned_bundle_element import OwnedBundleElement
from youtrack_api.model.project import Project
globals()['BundleProjectCustomField'] = BundleProjectCustomField
globals()['CustomField'] = CustomField
globals()['OwnedBundle'] = OwnedBundle
globals()['OwnedBundleCustomFieldDefaultsAllOf'] = OwnedBundleCustomFieldDefaultsAllOf
globals()['OwnedBundleElement'] = OwnedBundleElement
globals()['Project'] = Project
from youtrack_api.model.owned_project_custom_field import OwnedProjectCustomField


class TestOwnedProjectCustomField(unittest.TestCase):
    """OwnedProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnedProjectCustomField(self):
        """Test OwnedProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OwnedProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
