"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle_custom_field_defaults import BundleCustomFieldDefaults
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.enum_bundle import EnumBundle
from youtrack_api.model.enum_bundle_custom_field_defaults_all_of import EnumBundleCustomFieldDefaultsAllOf
from youtrack_api.model.enum_bundle_element import EnumBundleElement
globals()['BundleCustomFieldDefaults'] = BundleCustomFieldDefaults
globals()['CustomField'] = CustomField
globals()['EnumBundle'] = EnumBundle
globals()['EnumBundleCustomFieldDefaultsAllOf'] = EnumBundleCustomFieldDefaultsAllOf
globals()['EnumBundleElement'] = EnumBundleElement
from youtrack_api.model.enum_bundle_custom_field_defaults import EnumBundleCustomFieldDefaults


class TestEnumBundleCustomFieldDefaults(unittest.TestCase):
    """EnumBundleCustomFieldDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnumBundleCustomFieldDefaults(self):
        """Test EnumBundleCustomFieldDefaults"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnumBundleCustomFieldDefaults()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
