"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.sprint import Sprint
globals()['CustomField'] = CustomField
globals()['Sprint'] = Sprint
from youtrack_api.model.sprints_settings import SprintsSettings


class TestSprintsSettings(unittest.TestCase):
    """SprintsSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprintsSettings(self):
        """Test SprintsSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprintsSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
