"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.external_issue import ExternalIssue
from youtrack_api.model.issue_attachment import IssueAttachment
from youtrack_api.model.issue_comment import IssueComment
from youtrack_api.model.issue_custom_field import IssueCustomField
from youtrack_api.model.issue_link import IssueLink
from youtrack_api.model.issue_tag import IssueTag
from youtrack_api.model.issue_voters import IssueVoters
from youtrack_api.model.issue_watchers import IssueWatchers
from youtrack_api.model.project import Project
from youtrack_api.model.user import User
from youtrack_api.model.visibility import Visibility
globals()['ExternalIssue'] = ExternalIssue
globals()['IssueAttachment'] = IssueAttachment
globals()['IssueComment'] = IssueComment
globals()['IssueCustomField'] = IssueCustomField
globals()['IssueLink'] = IssueLink
globals()['IssueTag'] = IssueTag
globals()['IssueVoters'] = IssueVoters
globals()['IssueWatchers'] = IssueWatchers
globals()['Project'] = Project
globals()['User'] = User
globals()['Visibility'] = Visibility
from youtrack_api.model.issue import Issue


class TestIssue(unittest.TestCase):
    """Issue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssue(self):
        """Test Issue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Issue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
