"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_custom_field import IssueCustomField
from youtrack_api.model.text_field_value import TextFieldValue
from youtrack_api.model.text_issue_custom_field_all_of import TextIssueCustomFieldAllOf
globals()['IssueCustomField'] = IssueCustomField
globals()['TextFieldValue'] = TextFieldValue
globals()['TextIssueCustomFieldAllOf'] = TextIssueCustomFieldAllOf
from youtrack_api.model.text_issue_custom_field import TextIssueCustomField


class TestTextIssueCustomField(unittest.TestCase):
    """TextIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextIssueCustomField(self):
        """Test TextIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
