"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.user import User
from youtrack_api.model.user_bundle import UserBundle
globals()['User'] = User
globals()['UserBundle'] = UserBundle
from youtrack_api.model.user_custom_field_defaults_all_of import UserCustomFieldDefaultsAllOf


class TestUserCustomFieldDefaultsAllOf(unittest.TestCase):
    """UserCustomFieldDefaultsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCustomFieldDefaultsAllOf(self):
        """Test UserCustomFieldDefaultsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserCustomFieldDefaultsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
