"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.custom_field_defaults import CustomFieldDefaults
from youtrack_api.model.user import User
from youtrack_api.model.user_bundle import UserBundle
from youtrack_api.model.user_custom_field_defaults_all_of import UserCustomFieldDefaultsAllOf
globals()['CustomField'] = CustomField
globals()['CustomFieldDefaults'] = CustomFieldDefaults
globals()['User'] = User
globals()['UserBundle'] = UserBundle
globals()['UserCustomFieldDefaultsAllOf'] = UserCustomFieldDefaultsAllOf
from youtrack_api.model.user_custom_field_defaults import UserCustomFieldDefaults


class TestUserCustomFieldDefaults(unittest.TestCase):
    """UserCustomFieldDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCustomFieldDefaults(self):
        """Test UserCustomFieldDefaults"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserCustomFieldDefaults()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
