"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.multi_group_issue_custom_field_all_of import MultiGroupIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.user_group import UserGroup
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['MultiGroupIssueCustomFieldAllOf'] = MultiGroupIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['UserGroup'] = UserGroup
from youtrack_api.model.multi_group_issue_custom_field import MultiGroupIssueCustomField


class TestMultiGroupIssueCustomField(unittest.TestCase):
    """MultiGroupIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiGroupIssueCustomField(self):
        """Test MultiGroupIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiGroupIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
