"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.filter_field import FilterField
from youtrack_api.model.issue_based_swimlane_settings_all_of import IssueBasedSwimlaneSettingsAllOf
from youtrack_api.model.swimlane_settings import SwimlaneSettings
from youtrack_api.model.swimlane_value import SwimlaneValue
globals()['FilterField'] = FilterField
globals()['IssueBasedSwimlaneSettingsAllOf'] = IssueBasedSwimlaneSettingsAllOf
globals()['SwimlaneSettings'] = SwimlaneSettings
globals()['SwimlaneValue'] = SwimlaneValue
from youtrack_api.model.issue_based_swimlane_settings import IssueBasedSwimlaneSettings


class TestIssueBasedSwimlaneSettings(unittest.TestCase):
    """IssueBasedSwimlaneSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueBasedSwimlaneSettings(self):
        """Test IssueBasedSwimlaneSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueBasedSwimlaneSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
