"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_bundle import BuildBundle
from youtrack_api.model.build_bundle_element import BuildBundleElement
globals()['BuildBundle'] = BuildBundle
globals()['BuildBundleElement'] = BuildBundleElement
from youtrack_api.model.build_bundle_custom_field_defaults_all_of import BuildBundleCustomFieldDefaultsAllOf


class TestBuildBundleCustomFieldDefaultsAllOf(unittest.TestCase):
    """BuildBundleCustomFieldDefaultsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildBundleCustomFieldDefaultsAllOf(self):
        """Test BuildBundleCustomFieldDefaultsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BuildBundleCustomFieldDefaultsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
