"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_tag import IssueTag
from youtrack_api.model.saved_query import SavedQuery
from youtrack_api.model.user import User
from youtrack_api.model.user_profiles import UserProfiles
globals()['IssueTag'] = IssueTag
globals()['SavedQuery'] = SavedQuery
globals()['User'] = User
globals()['UserProfiles'] = UserProfiles
from youtrack_api.model.me import Me


class TestMe(unittest.TestCase):
    """Me unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMe(self):
        """Test Me"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Me()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
