"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.project import Project
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['CustomField'] = CustomField
globals()['Project'] = Project
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.period_project_custom_field import PeriodProjectCustomField


class TestPeriodProjectCustomField(unittest.TestCase):
    """PeriodProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriodProjectCustomField(self):
        """Test PeriodProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeriodProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
