"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.attribute_based_swimlane_settings_all_of import AttributeBasedSwimlaneSettingsAllOf
from youtrack_api.model.filter_field import FilterField
from youtrack_api.model.swimlane_entity_attribute_value import SwimlaneEntityAttributeValue
from youtrack_api.model.swimlane_settings import SwimlaneSettings
globals()['AttributeBasedSwimlaneSettingsAllOf'] = AttributeBasedSwimlaneSettingsAllOf
globals()['FilterField'] = FilterField
globals()['SwimlaneEntityAttributeValue'] = SwimlaneEntityAttributeValue
globals()['SwimlaneSettings'] = SwimlaneSettings
from youtrack_api.model.attribute_based_swimlane_settings import AttributeBasedSwimlaneSettings


class TestAttributeBasedSwimlaneSettings(unittest.TestCase):
    """AttributeBasedSwimlaneSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeBasedSwimlaneSettings(self):
        """Test AttributeBasedSwimlaneSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributeBasedSwimlaneSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
