"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.filter_field import FilterField
from youtrack_api.model.swimlane_entity_attribute_value import SwimlaneEntityAttributeValue
globals()['FilterField'] = FilterField
globals()['SwimlaneEntityAttributeValue'] = SwimlaneEntityAttributeValue
from youtrack_api.model.attribute_based_swimlane_settings_all_of import AttributeBasedSwimlaneSettingsAllOf


class TestAttributeBasedSwimlaneSettingsAllOf(unittest.TestCase):
    """AttributeBasedSwimlaneSettingsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeBasedSwimlaneSettingsAllOf(self):
        """Test AttributeBasedSwimlaneSettingsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttributeBasedSwimlaneSettingsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
