"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_bundle_custom_field_defaults import BuildBundleCustomFieldDefaults
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.custom_field_defaults import CustomFieldDefaults
from youtrack_api.model.enum_bundle_custom_field_defaults import EnumBundleCustomFieldDefaults
from youtrack_api.model.owned_bundle_custom_field_defaults import OwnedBundleCustomFieldDefaults
from youtrack_api.model.state_bundle_custom_field_defaults import StateBundleCustomFieldDefaults
from youtrack_api.model.version_bundle_custom_field_defaults import VersionBundleCustomFieldDefaults
globals()['BuildBundleCustomFieldDefaults'] = BuildBundleCustomFieldDefaults
globals()['CustomField'] = CustomField
globals()['CustomFieldDefaults'] = CustomFieldDefaults
globals()['EnumBundleCustomFieldDefaults'] = EnumBundleCustomFieldDefaults
globals()['OwnedBundleCustomFieldDefaults'] = OwnedBundleCustomFieldDefaults
globals()['StateBundleCustomFieldDefaults'] = StateBundleCustomFieldDefaults
globals()['VersionBundleCustomFieldDefaults'] = VersionBundleCustomFieldDefaults
from youtrack_api.model.bundle_custom_field_defaults import BundleCustomFieldDefaults


class TestBundleCustomFieldDefaults(unittest.TestCase):
    """BundleCustomFieldDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundleCustomFieldDefaults(self):
        """Test BundleCustomFieldDefaults"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BundleCustomFieldDefaults()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
