"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.enum_bundle_element import EnumBundleElement
globals()['EnumBundleElement'] = EnumBundleElement
from youtrack_api.model.multi_enum_issue_custom_field_all_of import MultiEnumIssueCustomFieldAllOf


class TestMultiEnumIssueCustomFieldAllOf(unittest.TestCase):
    """MultiEnumIssueCustomFieldAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiEnumIssueCustomFieldAllOf(self):
        """Test MultiEnumIssueCustomFieldAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiEnumIssueCustomFieldAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
