"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.activity_category import ActivityCategory


class TestActivityCategory(unittest.TestCase):
    """ActivityCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityCategory(self):
        """Test ActivityCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivityCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
