"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField
from youtrack_api.model.multi_owned_issue_custom_field_all_of import MultiOwnedIssueCustomFieldAllOf
from youtrack_api.model.owned_bundle_element import OwnedBundleElement
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['DatabaseSingleValueIssueCustomField'] = DatabaseSingleValueIssueCustomField
globals()['MultiOwnedIssueCustomFieldAllOf'] = MultiOwnedIssueCustomFieldAllOf
globals()['OwnedBundleElement'] = OwnedBundleElement
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.single_owned_issue_custom_field import SingleOwnedIssueCustomField


class TestSingleOwnedIssueCustomField(unittest.TestCase):
    """SingleOwnedIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleOwnedIssueCustomField(self):
        """Test SingleOwnedIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleOwnedIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
