"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField
from youtrack_api.model.multi_version_issue_custom_field_all_of import MultiVersionIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['DatabaseSingleValueIssueCustomField'] = DatabaseSingleValueIssueCustomField
globals()['MultiVersionIssueCustomFieldAllOf'] = MultiVersionIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.single_version_issue_custom_field import SingleVersionIssueCustomField


class TestSingleVersionIssueCustomField(unittest.TestCase):
    """SingleVersionIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleVersionIssueCustomField(self):
        """Test SingleVersionIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleVersionIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
