"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.user import User
from youtrack_api.model.visibility_activity_item import VisibilityActivityItem
from youtrack_api.model.visibility_user_activity_item_all_of import VisibilityUserActivityItemAllOf
globals()['User'] = User
globals()['VisibilityActivityItem'] = VisibilityActivityItem
globals()['VisibilityUserActivityItemAllOf'] = VisibilityUserActivityItemAllOf
from youtrack_api.model.visibility_user_activity_item import VisibilityUserActivityItem


class TestVisibilityUserActivityItem(unittest.TestCase):
    """VisibilityUserActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisibilityUserActivityItem(self):
        """Test VisibilityUserActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VisibilityUserActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
