"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue import Issue
globals()['Issue'] = Issue
from youtrack_api.model.saved_query_all_of import SavedQueryAllOf


class TestSavedQueryAllOf(unittest.TestCase):
    """SavedQueryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSavedQueryAllOf(self):
        """Test SavedQueryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SavedQueryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
