"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_bundle_element import BuildBundleElement
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.multi_build_issue_custom_field_all_of import MultiBuildIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['BuildBundleElement'] = BuildBundleElement
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['MultiBuildIssueCustomFieldAllOf'] = MultiBuildIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.multi_build_issue_custom_field import MultiBuildIssueCustomField


class TestMultiBuildIssueCustomField(unittest.TestCase):
    """MultiBuildIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiBuildIssueCustomField(self):
        """Test MultiBuildIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiBuildIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
