"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.duration_value import DurationValue
from youtrack_api.model.issue_work_item import IssueWorkItem
from youtrack_api.model.single_value_activity_item import SingleValueActivityItem
from youtrack_api.model.work_item_duration_activity_item_all_of import WorkItemDurationActivityItemAllOf
globals()['DurationValue'] = DurationValue
globals()['IssueWorkItem'] = IssueWorkItem
globals()['SingleValueActivityItem'] = SingleValueActivityItem
globals()['WorkItemDurationActivityItemAllOf'] = WorkItemDurationActivityItemAllOf
from youtrack_api.model.work_item_duration_activity_item import WorkItemDurationActivityItem


class TestWorkItemDurationActivityItem(unittest.TestCase):
    """WorkItemDurationActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkItemDurationActivityItem(self):
        """Test WorkItemDurationActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkItemDurationActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
