"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_comment import IssueComment
from youtrack_api.model.user_group import UserGroup
globals()['IssueComment'] = IssueComment
globals()['UserGroup'] = UserGroup
from youtrack_api.model.comment_activity_item_all_of import CommentActivityItemAllOf


class TestCommentActivityItemAllOf(unittest.TestCase):
    """CommentActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommentActivityItemAllOf(self):
        """Test CommentActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommentActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
