"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.user_group import UserGroup
globals()['UserGroup'] = UserGroup
from youtrack_api.model.visibility_group_activity_item_all_of import VisibilityGroupActivityItemAllOf


class TestVisibilityGroupActivityItemAllOf(unittest.TestCase):
    """VisibilityGroupActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisibilityGroupActivityItemAllOf(self):
        """Test VisibilityGroupActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VisibilityGroupActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
