"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle import Bundle
from youtrack_api.model.bundle_element import BundleElement
from youtrack_api.model.enum_bundle_element import EnumBundleElement
from youtrack_api.model.field_style import FieldStyle
from youtrack_api.model.localizable_bundle_element_all_of import LocalizableBundleElementAllOf
from youtrack_api.model.state_bundle_element import StateBundleElement
globals()['Bundle'] = Bundle
globals()['BundleElement'] = BundleElement
globals()['EnumBundleElement'] = EnumBundleElement
globals()['FieldStyle'] = FieldStyle
globals()['LocalizableBundleElementAllOf'] = LocalizableBundleElementAllOf
globals()['StateBundleElement'] = StateBundleElement
from youtrack_api.model.localizable_bundle_element import LocalizableBundleElement


class TestLocalizableBundleElement(unittest.TestCase):
    """LocalizableBundleElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalizableBundleElement(self):
        """Test LocalizableBundleElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalizableBundleElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
