"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.agile_column_field_value import AgileColumnFieldValue
from youtrack_api.model.swimlane_entity_attribute_value import SwimlaneEntityAttributeValue
globals()['AgileColumnFieldValue'] = AgileColumnFieldValue
globals()['SwimlaneEntityAttributeValue'] = SwimlaneEntityAttributeValue
from youtrack_api.model.database_attribute_value import DatabaseAttributeValue


class TestDatabaseAttributeValue(unittest.TestCase):
    """DatabaseAttributeValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabaseAttributeValue(self):
        """Test DatabaseAttributeValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatabaseAttributeValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
