"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue import Issue
from youtrack_api.model.issue_created_activity_item_all_of import IssueCreatedActivityItemAllOf
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
globals()['Issue'] = Issue
globals()['IssueCreatedActivityItemAllOf'] = IssueCreatedActivityItemAllOf
globals()['MultiValueActivityItem'] = MultiValueActivityItem
from youtrack_api.model.links_activity_item import LinksActivityItem


class TestLinksActivityItem(unittest.TestCase):
    """LinksActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinksActivityItem(self):
        """Test LinksActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LinksActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
