"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.base_bundle import BaseBundle
from youtrack_api.model.build_bundle_all_of import BuildBundleAllOf
from youtrack_api.model.build_bundle_element import BuildBundleElement
globals()['BaseBundle'] = BaseBundle
globals()['BuildBundleAllOf'] = BuildBundleAllOf
globals()['BuildBundleElement'] = BuildBundleElement
from youtrack_api.model.build_bundle import BuildBundle


class TestBuildBundle(unittest.TestCase):
    """BuildBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildBundle(self):
        """Test BuildBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BuildBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
