"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.base_bundle import BaseBundle
from youtrack_api.model.version_bundle_all_of import VersionBundleAllOf
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['BaseBundle'] = BaseBundle
globals()['VersionBundleAllOf'] = VersionBundleAllOf
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.version_bundle import VersionBundle


class TestVersionBundle(unittest.TestCase):
    """VersionBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionBundle(self):
        """Test VersionBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
