"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_bundle_element import BuildBundleElement
globals()['BuildBundleElement'] = BuildBundleElement
from youtrack_api.model.build_bundle_all_of import BuildBundleAllOf


class TestBuildBundleAllOf(unittest.TestCase):
    """BuildBundleAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildBundleAllOf(self):
        """Test BuildBundleAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BuildBundleAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
