"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle_custom_field_defaults import BundleCustomFieldDefaults
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.owned_bundle import OwnedBundle
from youtrack_api.model.owned_bundle_custom_field_defaults_all_of import OwnedBundleCustomFieldDefaultsAllOf
from youtrack_api.model.owned_bundle_element import OwnedBundleElement
globals()['BundleCustomFieldDefaults'] = BundleCustomFieldDefaults
globals()['CustomField'] = CustomField
globals()['OwnedBundle'] = OwnedBundle
globals()['OwnedBundleCustomFieldDefaultsAllOf'] = OwnedBundleCustomFieldDefaultsAllOf
globals()['OwnedBundleElement'] = OwnedBundleElement
from youtrack_api.model.owned_bundle_custom_field_defaults import OwnedBundleCustomFieldDefaults


class TestOwnedBundleCustomFieldDefaults(unittest.TestCase):
    """OwnedBundleCustomFieldDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnedBundleCustomFieldDefaults(self):
        """Test OwnedBundleCustomFieldDefaults"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OwnedBundleCustomFieldDefaults()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
