"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.command_visibility import CommandVisibility
globals()['CommandVisibility'] = CommandVisibility
from youtrack_api.model.command_unlimited_visibility import CommandUnlimitedVisibility


class TestCommandUnlimitedVisibility(unittest.TestCase):
    """CommandUnlimitedVisibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommandUnlimitedVisibility(self):
        """Test CommandUnlimitedVisibility"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandUnlimitedVisibility()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
