"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.multi_owned_issue_custom_field_all_of import MultiOwnedIssueCustomFieldAllOf
from youtrack_api.model.owned_bundle_element import OwnedBundleElement
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['MultiOwnedIssueCustomFieldAllOf'] = MultiOwnedIssueCustomFieldAllOf
globals()['OwnedBundleElement'] = OwnedBundleElement
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.multi_owned_issue_custom_field import MultiOwnedIssueCustomField


class TestMultiOwnedIssueCustomField(unittest.TestCase):
    """MultiOwnedIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiOwnedIssueCustomField(self):
        """Test MultiOwnedIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiOwnedIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
