"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle import Bundle
from youtrack_api.model.user import User
from youtrack_api.model.user_bundle_all_of import UserBundleAllOf
from youtrack_api.model.user_group import UserGroup
globals()['Bundle'] = Bundle
globals()['User'] = User
globals()['UserBundleAllOf'] = UserBundleAllOf
globals()['UserGroup'] = UserGroup
from youtrack_api.model.user_bundle import UserBundle


class TestUserBundle(unittest.TestCase):
    """UserBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBundle(self):
        """Test UserBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
