"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.base_bundle import BaseBundle
from youtrack_api.model.build_bundle import BuildBundle
from youtrack_api.model.enum_bundle import EnumBundle
from youtrack_api.model.owned_bundle import OwnedBundle
from youtrack_api.model.state_bundle import StateBundle
from youtrack_api.model.user_bundle import UserBundle
from youtrack_api.model.version_bundle import VersionBundle
globals()['BaseBundle'] = BaseBundle
globals()['BuildBundle'] = BuildBundle
globals()['EnumBundle'] = EnumBundle
globals()['OwnedBundle'] = OwnedBundle
globals()['StateBundle'] = StateBundle
globals()['UserBundle'] = UserBundle
globals()['VersionBundle'] = VersionBundle
from youtrack_api.model.bundle import Bundle


class TestBundle(unittest.TestCase):
    """Bundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundle(self):
        """Test Bundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Bundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
