"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.filter_field import FilterField
globals()['FilterField'] = FilterField
from youtrack_api.model.predefined_filter_field import PredefinedFilterField


class TestPredefinedFilterField(unittest.TestCase):
    """PredefinedFilterField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPredefinedFilterField(self):
        """Test PredefinedFilterField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PredefinedFilterField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
