"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.simple_value_activity_item import SimpleValueActivityItem
from youtrack_api.model.text_markup_activity_item_all_of import TextMarkupActivityItemAllOf
globals()['SimpleValueActivityItem'] = SimpleValueActivityItem
globals()['TextMarkupActivityItemAllOf'] = TextMarkupActivityItemAllOf
from youtrack_api.model.text_markup_activity_item import TextMarkupActivityItem


class TestTextMarkupActivityItem(unittest.TestCase):
    """TextMarkupActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextMarkupActivityItem(self):
        """Test TextMarkupActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextMarkupActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
