"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.state_bundle_element import StateBundleElement
globals()['StateBundleElement'] = StateBundleElement
from youtrack_api.model.state_issue_custom_field_all_of import StateIssueCustomFieldAllOf


class TestStateIssueCustomFieldAllOf(unittest.TestCase):
    """StateIssueCustomFieldAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateIssueCustomFieldAllOf(self):
        """Test StateIssueCustomFieldAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateIssueCustomFieldAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
