"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_tag import IssueTag
from youtrack_api.model.saved_query import SavedQuery
from youtrack_api.model.user import User
from youtrack_api.model.user_profiles import UserProfiles
from youtrack_api.model.vcs_unresolved_user_all_of import VcsUnresolvedUserAllOf
globals()['IssueTag'] = IssueTag
globals()['SavedQuery'] = SavedQuery
globals()['User'] = User
globals()['UserProfiles'] = UserProfiles
globals()['VcsUnresolvedUserAllOf'] = VcsUnresolvedUserAllOf
from youtrack_api.model.vcs_unresolved_user import VcsUnresolvedUser


class TestVcsUnresolvedUser(unittest.TestCase):
    """VcsUnresolvedUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVcsUnresolvedUser(self):
        """Test VcsUnresolvedUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VcsUnresolvedUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
