"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.group_project_custom_field_all_of import GroupProjectCustomFieldAllOf
from youtrack_api.model.project import Project
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.user_group import UserGroup
globals()['CustomField'] = CustomField
globals()['GroupProjectCustomFieldAllOf'] = GroupProjectCustomFieldAllOf
globals()['Project'] = Project
globals()['ProjectCustomField'] = ProjectCustomField
globals()['UserGroup'] = UserGroup
from youtrack_api.model.group_project_custom_field import GroupProjectCustomField


class TestGroupProjectCustomField(unittest.TestCase):
    """GroupProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupProjectCustomField(self):
        """Test GroupProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
