"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.user import User
globals()['User'] = User
from youtrack_api.model.multi_user_issue_custom_field_all_of import MultiUserIssueCustomFieldAllOf


class TestMultiUserIssueCustomFieldAllOf(unittest.TestCase):
    """MultiUserIssueCustomFieldAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiUserIssueCustomFieldAllOf(self):
        """Test MultiUserIssueCustomFieldAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiUserIssueCustomFieldAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
