"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField
from youtrack_api.model.multi_user_issue_custom_field_all_of import MultiUserIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.user import User
globals()['DatabaseSingleValueIssueCustomField'] = DatabaseSingleValueIssueCustomField
globals()['MultiUserIssueCustomFieldAllOf'] = MultiUserIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['User'] = User
from youtrack_api.model.single_user_issue_custom_field import SingleUserIssueCustomField


class TestSingleUserIssueCustomField(unittest.TestCase):
    """SingleUserIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleUserIssueCustomField(self):
        """Test SingleUserIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleUserIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
