"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.created_deleted_activity_item import CreatedDeletedActivityItem
from youtrack_api.model.issue_work_item import IssueWorkItem
from youtrack_api.model.work_item_activity_item_all_of import WorkItemActivityItemAllOf
globals()['CreatedDeletedActivityItem'] = CreatedDeletedActivityItem
globals()['IssueWorkItem'] = IssueWorkItem
globals()['WorkItemActivityItemAllOf'] = WorkItemActivityItemAllOf
from youtrack_api.model.work_item_activity_item import WorkItemActivityItem


class TestWorkItemActivityItem(unittest.TestCase):
    """WorkItemActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkItemActivityItem(self):
        """Test WorkItemActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkItemActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
