"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.agile_column_field_value import AgileColumnFieldValue
from youtrack_api.model.column_settings import ColumnSettings
from youtrack_api.model.wip_limit import WIPLimit
globals()['AgileColumnFieldValue'] = AgileColumnFieldValue
globals()['ColumnSettings'] = ColumnSettings
globals()['WIPLimit'] = WIPLimit
from youtrack_api.model.agile_column import AgileColumn


class TestAgileColumn(unittest.TestCase):
    """AgileColumn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgileColumn(self):
        """Test AgileColumn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgileColumn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
