"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_resolved_activity_item import IssueResolvedActivityItem
from youtrack_api.model.simple_value_activity_item_all_of import SimpleValueActivityItemAllOf
from youtrack_api.model.single_value_activity_item import SingleValueActivityItem
from youtrack_api.model.text_markup_activity_item import TextMarkupActivityItem
from youtrack_api.model.uses_markup_activity_item import UsesMarkupActivityItem
globals()['IssueResolvedActivityItem'] = IssueResolvedActivityItem
globals()['SimpleValueActivityItemAllOf'] = SimpleValueActivityItemAllOf
globals()['SingleValueActivityItem'] = SingleValueActivityItem
globals()['TextMarkupActivityItem'] = TextMarkupActivityItem
globals()['UsesMarkupActivityItem'] = UsesMarkupActivityItem
from youtrack_api.model.simple_value_activity_item import SimpleValueActivityItem


class TestSimpleValueActivityItem(unittest.TestCase):
    """SimpleValueActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleValueActivityItem(self):
        """Test SimpleValueActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimpleValueActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
