"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField
from youtrack_api.model.multi_group_issue_custom_field_all_of import MultiGroupIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.user_group import UserGroup
globals()['DatabaseSingleValueIssueCustomField'] = DatabaseSingleValueIssueCustomField
globals()['MultiGroupIssueCustomFieldAllOf'] = MultiGroupIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['UserGroup'] = UserGroup
from youtrack_api.model.single_group_issue_custom_field import SingleGroupIssueCustomField


class TestSingleGroupIssueCustomField(unittest.TestCase):
    """SingleGroupIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleGroupIssueCustomField(self):
        """Test SingleGroupIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleGroupIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
