"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field_all_of import DatabaseMultiValueIssueCustomFieldAllOf
from youtrack_api.model.issue_custom_field import IssueCustomField
from youtrack_api.model.multi_build_issue_custom_field import MultiBuildIssueCustomField
from youtrack_api.model.multi_enum_issue_custom_field import MultiEnumIssueCustomField
from youtrack_api.model.multi_group_issue_custom_field import MultiGroupIssueCustomField
from youtrack_api.model.multi_owned_issue_custom_field import MultiOwnedIssueCustomField
from youtrack_api.model.multi_user_issue_custom_field import MultiUserIssueCustomField
from youtrack_api.model.multi_version_issue_custom_field import MultiVersionIssueCustomField
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['DatabaseMultiValueIssueCustomFieldAllOf'] = DatabaseMultiValueIssueCustomFieldAllOf
globals()['IssueCustomField'] = IssueCustomField
globals()['MultiBuildIssueCustomField'] = MultiBuildIssueCustomField
globals()['MultiEnumIssueCustomField'] = MultiEnumIssueCustomField
globals()['MultiGroupIssueCustomField'] = MultiGroupIssueCustomField
globals()['MultiOwnedIssueCustomField'] = MultiOwnedIssueCustomField
globals()['MultiUserIssueCustomField'] = MultiUserIssueCustomField
globals()['MultiVersionIssueCustomField'] = MultiVersionIssueCustomField
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField


class TestDatabaseMultiValueIssueCustomField(unittest.TestCase):
    """DatabaseMultiValueIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabaseMultiValueIssueCustomField(self):
        """Test DatabaseMultiValueIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatabaseMultiValueIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
