"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.multi_version_issue_custom_field_all_of import MultiVersionIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['MultiVersionIssueCustomFieldAllOf'] = MultiVersionIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.multi_version_issue_custom_field import MultiVersionIssueCustomField


class TestMultiVersionIssueCustomField(unittest.TestCase):
    """MultiVersionIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiVersionIssueCustomField(self):
        """Test MultiVersionIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiVersionIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
