"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_bundle_element import BuildBundleElement
from youtrack_api.model.bundle import Bundle
from youtrack_api.model.enum_bundle_element import EnumBundleElement
from youtrack_api.model.field_style import FieldStyle
from youtrack_api.model.localizable_bundle_element import LocalizableBundleElement
from youtrack_api.model.owned_bundle_element import OwnedBundleElement
from youtrack_api.model.state_bundle_element import StateBundleElement
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['BuildBundleElement'] = BuildBundleElement
globals()['Bundle'] = Bundle
globals()['EnumBundleElement'] = EnumBundleElement
globals()['FieldStyle'] = FieldStyle
globals()['LocalizableBundleElement'] = LocalizableBundleElement
globals()['OwnedBundleElement'] = OwnedBundleElement
globals()['StateBundleElement'] = StateBundleElement
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.bundle_element import BundleElement


class TestBundleElement(unittest.TestCase):
    """BundleElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundleElement(self):
        """Test BundleElement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BundleElement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
