"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.date_format_descriptor import DateFormatDescriptor
from youtrack_api.model.locale_descriptor import LocaleDescriptor
from youtrack_api.model.time_zone_descriptor import TimeZoneDescriptor
globals()['DateFormatDescriptor'] = DateFormatDescriptor
globals()['LocaleDescriptor'] = LocaleDescriptor
globals()['TimeZoneDescriptor'] = TimeZoneDescriptor
from youtrack_api.model.general_user_profile import GeneralUserProfile


class TestGeneralUserProfile(unittest.TestCase):
    """GeneralUserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralUserProfile(self):
        """Test GeneralUserProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeneralUserProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
