"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.enum_bundle import EnumBundle
from youtrack_api.model.enum_bundle_element import EnumBundleElement
globals()['EnumBundle'] = EnumBundle
globals()['EnumBundleElement'] = EnumBundleElement
from youtrack_api.model.enum_bundle_custom_field_defaults_all_of import EnumBundleCustomFieldDefaultsAllOf


class TestEnumBundleCustomFieldDefaultsAllOf(unittest.TestCase):
    """EnumBundleCustomFieldDefaultsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnumBundleCustomFieldDefaultsAllOf(self):
        """Test EnumBundleCustomFieldDefaultsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnumBundleCustomFieldDefaultsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
