"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.project import Project
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.work_item_type import WorkItemType
globals()['Project'] = Project
globals()['ProjectCustomField'] = ProjectCustomField
globals()['WorkItemType'] = WorkItemType
from youtrack_api.model.project_time_tracking_settings import ProjectTimeTrackingSettings


class TestProjectTimeTrackingSettings(unittest.TestCase):
    """ProjectTimeTrackingSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectTimeTrackingSettings(self):
        """Test ProjectTimeTrackingSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectTimeTrackingSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
