"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_bundle import BuildBundle
from youtrack_api.model.build_bundle_custom_field_defaults_all_of import BuildBundleCustomFieldDefaultsAllOf
from youtrack_api.model.build_bundle_element import BuildBundleElement
from youtrack_api.model.bundle_project_custom_field import BundleProjectCustomField
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.project import Project
globals()['BuildBundle'] = BuildBundle
globals()['BuildBundleCustomFieldDefaultsAllOf'] = BuildBundleCustomFieldDefaultsAllOf
globals()['BuildBundleElement'] = BuildBundleElement
globals()['BundleProjectCustomField'] = BundleProjectCustomField
globals()['CustomField'] = CustomField
globals()['Project'] = Project
from youtrack_api.model.build_project_custom_field import BuildProjectCustomField


class TestBuildProjectCustomField(unittest.TestCase):
    """BuildProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildProjectCustomField(self):
        """Test BuildProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BuildProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
