"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.storage_entry import StorageEntry
globals()['StorageEntry'] = StorageEntry
from youtrack_api.model.email_settings import EmailSettings


class TestEmailSettings(unittest.TestCase):
    """EmailSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmailSettings(self):
        """Test EmailSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmailSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
