"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.appearance_settings import AppearanceSettings
from youtrack_api.model.license import License
from youtrack_api.model.locale_settings import LocaleSettings
from youtrack_api.model.notification_settings import NotificationSettings
from youtrack_api.model.rest_cors_settings import RestCorsSettings
from youtrack_api.model.system_settings import SystemSettings
globals()['AppearanceSettings'] = AppearanceSettings
globals()['License'] = License
globals()['LocaleSettings'] = LocaleSettings
globals()['NotificationSettings'] = NotificationSettings
globals()['RestCorsSettings'] = RestCorsSettings
globals()['SystemSettings'] = SystemSettings
from youtrack_api.model.global_settings import GlobalSettings


class TestGlobalSettings(unittest.TestCase):
    """GlobalSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalSettings(self):
        """Test GlobalSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GlobalSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
