"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.simple_value_activity_item_all_of import SimpleValueActivityItemAllOf


class TestSimpleValueActivityItemAllOf(unittest.TestCase):
    """SimpleValueActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleValueActivityItemAllOf(self):
        """Test SimpleValueActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimpleValueActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
