"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.date_format_descriptor import DateFormatDescriptor
from youtrack_api.model.logo import Logo
from youtrack_api.model.time_zone_descriptor import TimeZoneDescriptor
globals()['DateFormatDescriptor'] = DateFormatDescriptor
globals()['Logo'] = Logo
globals()['TimeZoneDescriptor'] = TimeZoneDescriptor
from youtrack_api.model.appearance_settings import AppearanceSettings


class TestAppearanceSettings(unittest.TestCase):
    """AppearanceSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppearanceSettings(self):
        """Test AppearanceSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AppearanceSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
