"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_work_item import IssueWorkItem
from youtrack_api.model.user import User
globals()['IssueWorkItem'] = IssueWorkItem
globals()['User'] = User
from youtrack_api.model.work_item_author_activity_item_all_of import WorkItemAuthorActivityItemAllOf


class TestWorkItemAuthorActivityItemAllOf(unittest.TestCase):
    """WorkItemAuthorActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkItemAuthorActivityItemAllOf(self):
        """Test WorkItemAuthorActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkItemAuthorActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
