"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.custom_field import CustomField
globals()['CustomField'] = CustomField
from youtrack_api.model.field_based_color_coding_all_of import FieldBasedColorCodingAllOf


class TestFieldBasedColorCodingAllOf(unittest.TestCase):
    """FieldBasedColorCodingAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldBasedColorCodingAllOf(self):
        """Test FieldBasedColorCodingAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldBasedColorCodingAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
