"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle_custom_field_defaults import BundleCustomFieldDefaults
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.state_bundle import StateBundle
from youtrack_api.model.state_bundle_custom_field_defaults_all_of import StateBundleCustomFieldDefaultsAllOf
from youtrack_api.model.state_bundle_element import StateBundleElement
globals()['BundleCustomFieldDefaults'] = BundleCustomFieldDefaults
globals()['CustomField'] = CustomField
globals()['StateBundle'] = StateBundle
globals()['StateBundleCustomFieldDefaultsAllOf'] = StateBundleCustomFieldDefaultsAllOf
globals()['StateBundleElement'] = StateBundleElement
from youtrack_api.model.state_bundle_custom_field_defaults import StateBundleCustomFieldDefaults


class TestStateBundleCustomFieldDefaults(unittest.TestCase):
    """StateBundleCustomFieldDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateBundleCustomFieldDefaults(self):
        """Test StateBundleCustomFieldDefaults"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateBundleCustomFieldDefaults()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
