"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.version_bundle_element import VersionBundleElement
globals()['VersionBundleElement'] = VersionBundleElement
from youtrack_api.model.multi_version_issue_custom_field_all_of import MultiVersionIssueCustomFieldAllOf


class TestMultiVersionIssueCustomFieldAllOf(unittest.TestCase):
    """MultiVersionIssueCustomFieldAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiVersionIssueCustomFieldAllOf(self):
        """Test MultiVersionIssueCustomFieldAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiVersionIssueCustomFieldAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
