"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.user_group import UserGroup
from youtrack_api.model.visibility_activity_item import VisibilityActivityItem
from youtrack_api.model.visibility_group_activity_item_all_of import VisibilityGroupActivityItemAllOf
globals()['UserGroup'] = UserGroup
globals()['VisibilityActivityItem'] = VisibilityActivityItem
globals()['VisibilityGroupActivityItemAllOf'] = VisibilityGroupActivityItemAllOf
from youtrack_api.model.visibility_group_activity_item import VisibilityGroupActivityItem


class TestVisibilityGroupActivityItem(unittest.TestCase):
    """VisibilityGroupActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisibilityGroupActivityItem(self):
        """Test VisibilityGroupActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VisibilityGroupActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
