"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.email_settings import EmailSettings
from youtrack_api.model.jabber_settings import JabberSettings
globals()['EmailSettings'] = EmailSettings
globals()['JabberSettings'] = JabberSettings
from youtrack_api.model.notification_settings import NotificationSettings


class TestNotificationSettings(unittest.TestCase):
    """NotificationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationSettings(self):
        """Test NotificationSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
