"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.backup_error import BackupError
globals()['BackupError'] = BackupError
from youtrack_api.model.backup_status import BackupStatus


class TestBackupStatus(unittest.TestCase):
    """BackupStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupStatus(self):
        """Test BackupStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BackupStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
