"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.field_based_color_coding import FieldBasedColorCoding
from youtrack_api.model.project_based_color_coding import ProjectBasedColorCoding
globals()['FieldBasedColorCoding'] = FieldBasedColorCoding
globals()['ProjectBasedColorCoding'] = ProjectBasedColorCoding
from youtrack_api.model.color_coding import ColorCoding


class TestColorCoding(unittest.TestCase):
    """ColorCoding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColorCoding(self):
        """Test ColorCoding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ColorCoding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
