"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.text_field_value import TextFieldValue


class TestTextFieldValue(unittest.TestCase):
    """TextFieldValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextFieldValue(self):
        """Test TextFieldValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextFieldValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
