"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.created_deleted_activity_item import CreatedDeletedActivityItem
from youtrack_api.model.user import User
from youtrack_api.model.vcs_change_activity_item_all_of import VcsChangeActivityItemAllOf
globals()['CreatedDeletedActivityItem'] = CreatedDeletedActivityItem
globals()['User'] = User
globals()['VcsChangeActivityItemAllOf'] = VcsChangeActivityItemAllOf
from youtrack_api.model.vcs_change_activity_item import VcsChangeActivityItem


class TestVcsChangeActivityItem(unittest.TestCase):
    """VcsChangeActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVcsChangeActivityItem(self):
        """Test VcsChangeActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VcsChangeActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
