"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.period_field_format import PeriodFieldFormat
globals()['PeriodFieldFormat'] = PeriodFieldFormat
from youtrack_api.model.time_tracking_user_profile import TimeTrackingUserProfile


class TestTimeTrackingUserProfile(unittest.TestCase):
    """TimeTrackingUserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeTrackingUserProfile(self):
        """Test TimeTrackingUserProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeTrackingUserProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
