"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.agile_column import AgileColumn
from youtrack_api.model.custom_field import CustomField
globals()['AgileColumn'] = AgileColumn
globals()['CustomField'] = CustomField
from youtrack_api.model.column_settings import ColumnSettings


class TestColumnSettings(unittest.TestCase):
    """ColumnSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumnSettings(self):
        """Test ColumnSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ColumnSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
