"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.base_bundle import BaseBundle
from youtrack_api.model.owned_bundle_all_of import OwnedBundleAllOf
from youtrack_api.model.owned_bundle_element import OwnedBundleElement
globals()['BaseBundle'] = BaseBundle
globals()['OwnedBundleAllOf'] = OwnedBundleAllOf
globals()['OwnedBundleElement'] = OwnedBundleElement
from youtrack_api.model.owned_bundle import OwnedBundle


class TestOwnedBundle(unittest.TestCase):
    """OwnedBundle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnedBundle(self):
        """Test OwnedBundle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OwnedBundle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
