"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.filter_field import FilterField
from youtrack_api.model.swimlane_value import SwimlaneValue
globals()['FilterField'] = FilterField
globals()['SwimlaneValue'] = SwimlaneValue
from youtrack_api.model.issue_based_swimlane_settings_all_of import IssueBasedSwimlaneSettingsAllOf


class TestIssueBasedSwimlaneSettingsAllOf(unittest.TestCase):
    """IssueBasedSwimlaneSettingsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueBasedSwimlaneSettingsAllOf(self):
        """Test IssueBasedSwimlaneSettingsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueBasedSwimlaneSettingsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
