"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.activity_item import ActivityItem
from youtrack_api.model.issue_resolved_activity_item import IssueResolvedActivityItem
from youtrack_api.model.project_activity_item import ProjectActivityItem
from youtrack_api.model.simple_value_activity_item import SimpleValueActivityItem
from youtrack_api.model.text_markup_activity_item import TextMarkupActivityItem
from youtrack_api.model.uses_markup_activity_item import UsesMarkupActivityItem
from youtrack_api.model.work_item_author_activity_item import WorkItemAuthorActivityItem
from youtrack_api.model.work_item_duration_activity_item import WorkItemDurationActivityItem
globals()['ActivityItem'] = ActivityItem
globals()['IssueResolvedActivityItem'] = IssueResolvedActivityItem
globals()['ProjectActivityItem'] = ProjectActivityItem
globals()['SimpleValueActivityItem'] = SimpleValueActivityItem
globals()['TextMarkupActivityItem'] = TextMarkupActivityItem
globals()['UsesMarkupActivityItem'] = UsesMarkupActivityItem
globals()['WorkItemAuthorActivityItem'] = WorkItemAuthorActivityItem
globals()['WorkItemDurationActivityItem'] = WorkItemDurationActivityItem
from youtrack_api.model.single_value_activity_item import SingleValueActivityItem


class TestSingleValueActivityItem(unittest.TestCase):
    """SingleValueActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleValueActivityItem(self):
        """Test SingleValueActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleValueActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
