"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.attachment_activity_item import AttachmentActivityItem
from youtrack_api.model.comment_activity_item import CommentActivityItem
from youtrack_api.model.comment_attachments_activity_item import CommentAttachmentsActivityItem
from youtrack_api.model.created_deleted_activity_item import CreatedDeletedActivityItem
from youtrack_api.model.custom_field_activity_item import CustomFieldActivityItem
from youtrack_api.model.issue_created_activity_item import IssueCreatedActivityItem
from youtrack_api.model.issue_resolved_activity_item import IssueResolvedActivityItem
from youtrack_api.model.links_activity_item import LinksActivityItem
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
from youtrack_api.model.project_activity_item import ProjectActivityItem
from youtrack_api.model.simple_value_activity_item import SimpleValueActivityItem
from youtrack_api.model.single_value_activity_item import SingleValueActivityItem
from youtrack_api.model.sprint_activity_item import SprintActivityItem
from youtrack_api.model.tags_activity_item import TagsActivityItem
from youtrack_api.model.text_custom_field_activity_item import TextCustomFieldActivityItem
from youtrack_api.model.text_markup_activity_item import TextMarkupActivityItem
from youtrack_api.model.uses_markup_activity_item import UsesMarkupActivityItem
from youtrack_api.model.vcs_change_activity_item import VcsChangeActivityItem
from youtrack_api.model.visibility_activity_item import VisibilityActivityItem
from youtrack_api.model.visibility_group_activity_item import VisibilityGroupActivityItem
from youtrack_api.model.visibility_user_activity_item import VisibilityUserActivityItem
from youtrack_api.model.voters_activity_item import VotersActivityItem
from youtrack_api.model.work_item_activity_item import WorkItemActivityItem
from youtrack_api.model.work_item_author_activity_item import WorkItemAuthorActivityItem
from youtrack_api.model.work_item_duration_activity_item import WorkItemDurationActivityItem
from youtrack_api.model.work_item_type_activity_item import WorkItemTypeActivityItem
globals()['AttachmentActivityItem'] = AttachmentActivityItem
globals()['CommentActivityItem'] = CommentActivityItem
globals()['CommentAttachmentsActivityItem'] = CommentAttachmentsActivityItem
globals()['CreatedDeletedActivityItem'] = CreatedDeletedActivityItem
globals()['CustomFieldActivityItem'] = CustomFieldActivityItem
globals()['IssueCreatedActivityItem'] = IssueCreatedActivityItem
globals()['IssueResolvedActivityItem'] = IssueResolvedActivityItem
globals()['LinksActivityItem'] = LinksActivityItem
globals()['MultiValueActivityItem'] = MultiValueActivityItem
globals()['ProjectActivityItem'] = ProjectActivityItem
globals()['SimpleValueActivityItem'] = SimpleValueActivityItem
globals()['SingleValueActivityItem'] = SingleValueActivityItem
globals()['SprintActivityItem'] = SprintActivityItem
globals()['TagsActivityItem'] = TagsActivityItem
globals()['TextCustomFieldActivityItem'] = TextCustomFieldActivityItem
globals()['TextMarkupActivityItem'] = TextMarkupActivityItem
globals()['UsesMarkupActivityItem'] = UsesMarkupActivityItem
globals()['VcsChangeActivityItem'] = VcsChangeActivityItem
globals()['VisibilityActivityItem'] = VisibilityActivityItem
globals()['VisibilityGroupActivityItem'] = VisibilityGroupActivityItem
globals()['VisibilityUserActivityItem'] = VisibilityUserActivityItem
globals()['VotersActivityItem'] = VotersActivityItem
globals()['WorkItemActivityItem'] = WorkItemActivityItem
globals()['WorkItemAuthorActivityItem'] = WorkItemAuthorActivityItem
globals()['WorkItemDurationActivityItem'] = WorkItemDurationActivityItem
globals()['WorkItemTypeActivityItem'] = WorkItemTypeActivityItem
from youtrack_api.model.activity_item import ActivityItem


class TestActivityItem(unittest.TestCase):
    """ActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityItem(self):
        """Test ActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
