"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.issue_custom_field import IssueCustomField
from youtrack_api.model.period_issue_custom_field_all_of import PeriodIssueCustomFieldAllOf
from youtrack_api.model.period_value import PeriodValue
globals()['IssueCustomField'] = IssueCustomField
globals()['PeriodIssueCustomFieldAllOf'] = PeriodIssueCustomFieldAllOf
globals()['PeriodValue'] = PeriodValue
from youtrack_api.model.period_issue_custom_field import PeriodIssueCustomField


class TestPeriodIssueCustomField(unittest.TestCase):
    """PeriodIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriodIssueCustomField(self):
        """Test PeriodIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeriodIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
