"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.date_issue_custom_field_all_of import DateIssueCustomFieldAllOf
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.simple_issue_custom_field import SimpleIssueCustomField
globals()['DateIssueCustomFieldAllOf'] = DateIssueCustomFieldAllOf
globals()['ProjectCustomField'] = ProjectCustomField
globals()['SimpleIssueCustomField'] = SimpleIssueCustomField
from youtrack_api.model.date_issue_custom_field import DateIssueCustomField


class TestDateIssueCustomField(unittest.TestCase):
    """DateIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDateIssueCustomField(self):
        """Test DateIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DateIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
