"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.color_coding import ColorCoding
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.field_based_color_coding_all_of import FieldBasedColorCodingAllOf
globals()['ColorCoding'] = ColorCoding
globals()['CustomField'] = CustomField
globals()['FieldBasedColorCodingAllOf'] = FieldBasedColorCodingAllOf
from youtrack_api.model.field_based_color_coding import FieldBasedColorCoding


class TestFieldBasedColorCoding(unittest.TestCase):
    """FieldBasedColorCoding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldBasedColorCoding(self):
        """Test FieldBasedColorCoding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FieldBasedColorCoding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
