"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.bundle_project_custom_field import BundleProjectCustomField
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.enum_bundle import EnumBundle
from youtrack_api.model.enum_bundle_custom_field_defaults_all_of import EnumBundleCustomFieldDefaultsAllOf
from youtrack_api.model.enum_bundle_element import EnumBundleElement
from youtrack_api.model.project import Project
globals()['BundleProjectCustomField'] = BundleProjectCustomField
globals()['CustomField'] = CustomField
globals()['EnumBundle'] = EnumBundle
globals()['EnumBundleCustomFieldDefaultsAllOf'] = EnumBundleCustomFieldDefaultsAllOf
globals()['EnumBundleElement'] = EnumBundleElement
globals()['Project'] = Project
from youtrack_api.model.enum_project_custom_field import EnumProjectCustomField


class TestEnumProjectCustomField(unittest.TestCase):
    """EnumProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnumProjectCustomField(self):
        """Test EnumProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnumProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
