"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field_all_of import DatabaseMultiValueIssueCustomFieldAllOf
from youtrack_api.model.date_issue_custom_field import DateIssueCustomField
from youtrack_api.model.issue_custom_field import IssueCustomField
from youtrack_api.model.project_custom_field import ProjectCustomField
globals()['DatabaseMultiValueIssueCustomFieldAllOf'] = DatabaseMultiValueIssueCustomFieldAllOf
globals()['DateIssueCustomField'] = DateIssueCustomField
globals()['IssueCustomField'] = IssueCustomField
globals()['ProjectCustomField'] = ProjectCustomField
from youtrack_api.model.simple_issue_custom_field import SimpleIssueCustomField


class TestSimpleIssueCustomField(unittest.TestCase):
    """SimpleIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleIssueCustomField(self):
        """Test SimpleIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SimpleIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
