"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.user import User
globals()['User'] = User
from youtrack_api.model.vcs_change_activity_item_all_of import VcsChangeActivityItemAllOf


class TestVcsChangeActivityItemAllOf(unittest.TestCase):
    """VcsChangeActivityItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVcsChangeActivityItemAllOf(self):
        """Test VcsChangeActivityItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VcsChangeActivityItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
