"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field_all_of import DatabaseMultiValueIssueCustomFieldAllOf
from youtrack_api.model.issue_custom_field import IssueCustomField
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.single_build_issue_custom_field import SingleBuildIssueCustomField
from youtrack_api.model.single_enum_issue_custom_field import SingleEnumIssueCustomField
from youtrack_api.model.single_group_issue_custom_field import SingleGroupIssueCustomField
from youtrack_api.model.single_owned_issue_custom_field import SingleOwnedIssueCustomField
from youtrack_api.model.single_user_issue_custom_field import SingleUserIssueCustomField
from youtrack_api.model.single_version_issue_custom_field import SingleVersionIssueCustomField
from youtrack_api.model.state_issue_custom_field import StateIssueCustomField
globals()['DatabaseMultiValueIssueCustomFieldAllOf'] = DatabaseMultiValueIssueCustomFieldAllOf
globals()['IssueCustomField'] = IssueCustomField
globals()['ProjectCustomField'] = ProjectCustomField
globals()['SingleBuildIssueCustomField'] = SingleBuildIssueCustomField
globals()['SingleEnumIssueCustomField'] = SingleEnumIssueCustomField
globals()['SingleGroupIssueCustomField'] = SingleGroupIssueCustomField
globals()['SingleOwnedIssueCustomField'] = SingleOwnedIssueCustomField
globals()['SingleUserIssueCustomField'] = SingleUserIssueCustomField
globals()['SingleVersionIssueCustomField'] = SingleVersionIssueCustomField
globals()['StateIssueCustomField'] = StateIssueCustomField
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField


class TestDatabaseSingleValueIssueCustomField(unittest.TestCase):
    """DatabaseSingleValueIssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabaseSingleValueIssueCustomField(self):
        """Test DatabaseSingleValueIssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatabaseSingleValueIssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
