"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.build_project_custom_field import BuildProjectCustomField
from youtrack_api.model.custom_field import CustomField
from youtrack_api.model.enum_project_custom_field import EnumProjectCustomField
from youtrack_api.model.owned_project_custom_field import OwnedProjectCustomField
from youtrack_api.model.project import Project
from youtrack_api.model.project_custom_field import ProjectCustomField
from youtrack_api.model.state_project_custom_field import StateProjectCustomField
from youtrack_api.model.user_project_custom_field import UserProjectCustomField
from youtrack_api.model.version_project_custom_field import VersionProjectCustomField
globals()['BuildProjectCustomField'] = BuildProjectCustomField
globals()['CustomField'] = CustomField
globals()['EnumProjectCustomField'] = EnumProjectCustomField
globals()['OwnedProjectCustomField'] = OwnedProjectCustomField
globals()['Project'] = Project
globals()['ProjectCustomField'] = ProjectCustomField
globals()['StateProjectCustomField'] = StateProjectCustomField
globals()['UserProjectCustomField'] = UserProjectCustomField
globals()['VersionProjectCustomField'] = VersionProjectCustomField
from youtrack_api.model.bundle_project_custom_field import BundleProjectCustomField


class TestBundleProjectCustomField(unittest.TestCase):
    """BundleProjectCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundleProjectCustomField(self):
        """Test BundleProjectCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BundleProjectCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
