"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.database_multi_value_issue_custom_field import DatabaseMultiValueIssueCustomField
from youtrack_api.model.database_single_value_issue_custom_field import DatabaseSingleValueIssueCustomField
from youtrack_api.model.date_issue_custom_field import DateIssueCustomField
from youtrack_api.model.multi_build_issue_custom_field import MultiBuildIssueCustomField
from youtrack_api.model.multi_enum_issue_custom_field import MultiEnumIssueCustomField
from youtrack_api.model.multi_group_issue_custom_field import MultiGroupIssueCustomField
from youtrack_api.model.multi_owned_issue_custom_field import MultiOwnedIssueCustomField
from youtrack_api.model.multi_user_issue_custom_field import MultiUserIssueCustomField
from youtrack_api.model.multi_version_issue_custom_field import MultiVersionIssueCustomField
from youtrack_api.model.period_issue_custom_field import PeriodIssueCustomField
from youtrack_api.model.simple_issue_custom_field import SimpleIssueCustomField
from youtrack_api.model.single_build_issue_custom_field import SingleBuildIssueCustomField
from youtrack_api.model.single_enum_issue_custom_field import SingleEnumIssueCustomField
from youtrack_api.model.single_group_issue_custom_field import SingleGroupIssueCustomField
from youtrack_api.model.single_owned_issue_custom_field import SingleOwnedIssueCustomField
from youtrack_api.model.single_user_issue_custom_field import SingleUserIssueCustomField
from youtrack_api.model.single_version_issue_custom_field import SingleVersionIssueCustomField
from youtrack_api.model.state_issue_custom_field import StateIssueCustomField
from youtrack_api.model.text_issue_custom_field import TextIssueCustomField
globals()['DatabaseMultiValueIssueCustomField'] = DatabaseMultiValueIssueCustomField
globals()['DatabaseSingleValueIssueCustomField'] = DatabaseSingleValueIssueCustomField
globals()['DateIssueCustomField'] = DateIssueCustomField
globals()['MultiBuildIssueCustomField'] = MultiBuildIssueCustomField
globals()['MultiEnumIssueCustomField'] = MultiEnumIssueCustomField
globals()['MultiGroupIssueCustomField'] = MultiGroupIssueCustomField
globals()['MultiOwnedIssueCustomField'] = MultiOwnedIssueCustomField
globals()['MultiUserIssueCustomField'] = MultiUserIssueCustomField
globals()['MultiVersionIssueCustomField'] = MultiVersionIssueCustomField
globals()['PeriodIssueCustomField'] = PeriodIssueCustomField
globals()['SimpleIssueCustomField'] = SimpleIssueCustomField
globals()['SingleBuildIssueCustomField'] = SingleBuildIssueCustomField
globals()['SingleEnumIssueCustomField'] = SingleEnumIssueCustomField
globals()['SingleGroupIssueCustomField'] = SingleGroupIssueCustomField
globals()['SingleOwnedIssueCustomField'] = SingleOwnedIssueCustomField
globals()['SingleUserIssueCustomField'] = SingleUserIssueCustomField
globals()['SingleVersionIssueCustomField'] = SingleVersionIssueCustomField
globals()['StateIssueCustomField'] = StateIssueCustomField
globals()['TextIssueCustomField'] = TextIssueCustomField
from youtrack_api.model.issue_custom_field import IssueCustomField


class TestIssueCustomField(unittest.TestCase):
    """IssueCustomField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueCustomField(self):
        """Test IssueCustomField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueCustomField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
