"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import youtrack_api
from youtrack_api.model.activity_item import ActivityItem
from youtrack_api.model.comment_attachments_activity_item import CommentAttachmentsActivityItem
from youtrack_api.model.links_activity_item import LinksActivityItem
from youtrack_api.model.sprint_activity_item import SprintActivityItem
from youtrack_api.model.tags_activity_item import TagsActivityItem
from youtrack_api.model.visibility_activity_item import VisibilityActivityItem
from youtrack_api.model.visibility_group_activity_item import VisibilityGroupActivityItem
from youtrack_api.model.visibility_user_activity_item import VisibilityUserActivityItem
from youtrack_api.model.voters_activity_item import VotersActivityItem
from youtrack_api.model.work_item_type_activity_item import WorkItemTypeActivityItem
globals()['ActivityItem'] = ActivityItem
globals()['CommentAttachmentsActivityItem'] = CommentAttachmentsActivityItem
globals()['LinksActivityItem'] = LinksActivityItem
globals()['SprintActivityItem'] = SprintActivityItem
globals()['TagsActivityItem'] = TagsActivityItem
globals()['VisibilityActivityItem'] = VisibilityActivityItem
globals()['VisibilityGroupActivityItem'] = VisibilityGroupActivityItem
globals()['VisibilityUserActivityItem'] = VisibilityUserActivityItem
globals()['VotersActivityItem'] = VotersActivityItem
globals()['WorkItemTypeActivityItem'] = WorkItemTypeActivityItem
from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem


class TestMultiValueActivityItem(unittest.TestCase):
    """MultiValueActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiValueActivityItem(self):
        """Test MultiValueActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiValueActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
