"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from youtrack_api.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from youtrack_api.exceptions import ApiAttributeError


def lazy_import():
    from youtrack_api.model.attachment_activity_item import AttachmentActivityItem
    from youtrack_api.model.comment_activity_item import CommentActivityItem
    from youtrack_api.model.comment_attachments_activity_item import CommentAttachmentsActivityItem
    from youtrack_api.model.created_deleted_activity_item import CreatedDeletedActivityItem
    from youtrack_api.model.custom_field_activity_item import CustomFieldActivityItem
    from youtrack_api.model.issue_created_activity_item import IssueCreatedActivityItem
    from youtrack_api.model.issue_resolved_activity_item import IssueResolvedActivityItem
    from youtrack_api.model.links_activity_item import LinksActivityItem
    from youtrack_api.model.multi_value_activity_item import MultiValueActivityItem
    from youtrack_api.model.project_activity_item import ProjectActivityItem
    from youtrack_api.model.simple_value_activity_item import SimpleValueActivityItem
    from youtrack_api.model.single_value_activity_item import SingleValueActivityItem
    from youtrack_api.model.sprint_activity_item import SprintActivityItem
    from youtrack_api.model.tags_activity_item import TagsActivityItem
    from youtrack_api.model.text_custom_field_activity_item import TextCustomFieldActivityItem
    from youtrack_api.model.text_markup_activity_item import TextMarkupActivityItem
    from youtrack_api.model.uses_markup_activity_item import UsesMarkupActivityItem
    from youtrack_api.model.vcs_change_activity_item import VcsChangeActivityItem
    from youtrack_api.model.visibility_activity_item import VisibilityActivityItem
    from youtrack_api.model.visibility_group_activity_item import VisibilityGroupActivityItem
    from youtrack_api.model.visibility_user_activity_item import VisibilityUserActivityItem
    from youtrack_api.model.voters_activity_item import VotersActivityItem
    from youtrack_api.model.work_item_activity_item import WorkItemActivityItem
    from youtrack_api.model.work_item_author_activity_item import WorkItemAuthorActivityItem
    from youtrack_api.model.work_item_duration_activity_item import WorkItemDurationActivityItem
    from youtrack_api.model.work_item_type_activity_item import WorkItemTypeActivityItem
    globals()['AttachmentActivityItem'] = AttachmentActivityItem
    globals()['CommentActivityItem'] = CommentActivityItem
    globals()['CommentAttachmentsActivityItem'] = CommentAttachmentsActivityItem
    globals()['CreatedDeletedActivityItem'] = CreatedDeletedActivityItem
    globals()['CustomFieldActivityItem'] = CustomFieldActivityItem
    globals()['IssueCreatedActivityItem'] = IssueCreatedActivityItem
    globals()['IssueResolvedActivityItem'] = IssueResolvedActivityItem
    globals()['LinksActivityItem'] = LinksActivityItem
    globals()['MultiValueActivityItem'] = MultiValueActivityItem
    globals()['ProjectActivityItem'] = ProjectActivityItem
    globals()['SimpleValueActivityItem'] = SimpleValueActivityItem
    globals()['SingleValueActivityItem'] = SingleValueActivityItem
    globals()['SprintActivityItem'] = SprintActivityItem
    globals()['TagsActivityItem'] = TagsActivityItem
    globals()['TextCustomFieldActivityItem'] = TextCustomFieldActivityItem
    globals()['TextMarkupActivityItem'] = TextMarkupActivityItem
    globals()['UsesMarkupActivityItem'] = UsesMarkupActivityItem
    globals()['VcsChangeActivityItem'] = VcsChangeActivityItem
    globals()['VisibilityActivityItem'] = VisibilityActivityItem
    globals()['VisibilityGroupActivityItem'] = VisibilityGroupActivityItem
    globals()['VisibilityUserActivityItem'] = VisibilityUserActivityItem
    globals()['VotersActivityItem'] = VotersActivityItem
    globals()['WorkItemActivityItem'] = WorkItemActivityItem
    globals()['WorkItemAuthorActivityItem'] = WorkItemAuthorActivityItem
    globals()['WorkItemDurationActivityItem'] = WorkItemDurationActivityItem
    globals()['WorkItemTypeActivityItem'] = WorkItemTypeActivityItem


class ActivityItem(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        lazy_import()
        val = {
            'AttachmentActivityItem': AttachmentActivityItem,
            'CommentActivityItem': CommentActivityItem,
            'CommentAttachmentsActivityItem': CommentAttachmentsActivityItem,
            'CreatedDeletedActivityItem': CreatedDeletedActivityItem,
            'CustomFieldActivityItem': CustomFieldActivityItem,
            'IssueCreatedActivityItem': IssueCreatedActivityItem,
            'IssueResolvedActivityItem': IssueResolvedActivityItem,
            'LinksActivityItem': LinksActivityItem,
            'MultiValueActivityItem': MultiValueActivityItem,
            'ProjectActivityItem': ProjectActivityItem,
            'SimpleValueActivityItem': SimpleValueActivityItem,
            'SingleValueActivityItem': SingleValueActivityItem,
            'SprintActivityItem': SprintActivityItem,
            'TagsActivityItem': TagsActivityItem,
            'TextCustomFieldActivityItem': TextCustomFieldActivityItem,
            'TextMarkupActivityItem': TextMarkupActivityItem,
            'UsesMarkupActivityItem': UsesMarkupActivityItem,
            'VcsChangeActivityItem': VcsChangeActivityItem,
            'VisibilityActivityItem': VisibilityActivityItem,
            'VisibilityGroupActivityItem': VisibilityGroupActivityItem,
            'VisibilityUserActivityItem': VisibilityUserActivityItem,
            'VotersActivityItem': VotersActivityItem,
            'WorkItemActivityItem': WorkItemActivityItem,
            'WorkItemAuthorActivityItem': WorkItemAuthorActivityItem,
            'WorkItemDurationActivityItem': WorkItemDurationActivityItem,
            'WorkItemTypeActivityItem': WorkItemTypeActivityItem,
        }
        if not val:
            return None
        return {'type': val}

    attribute_map = {
        'id': 'id',  # noqa: E501
        'type': '$type',  # noqa: E501
    }

    read_only_vars = {
        'id',  # noqa: E501
        'type',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ActivityItem - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ActivityItem - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
