"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from youtrack_api.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from youtrack_api.exceptions import ApiAttributeError


def lazy_import():
    from youtrack_api.model.online_users import OnlineUsers
    globals()['OnlineUsers'] = OnlineUsers


class Telemetry(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'installation_folder': (str,),  # noqa: E501
            'database_location': (str,),  # noqa: E501
            'logs_location': (str,),  # noqa: E501
            'available_processors': (int,),  # noqa: E501
            'available_memory': (str,),  # noqa: E501
            'allocated_memory': (str,),  # noqa: E501
            'used_memory': (str,),  # noqa: E501
            'uptime': (str,),  # noqa: E501
            'started_time': (int,),  # noqa: E501
            'database_background_threads': (int,),  # noqa: E501
            'pending_async_jobs': (int,),  # noqa: E501
            'cached_results_count_in_db_queries_cache': (int,),  # noqa: E501
            'database_queries_cache_hit_rate': (str,),  # noqa: E501
            'blob_strings_cache_hit_rate': (str,),  # noqa: E501
            'total_transactions': (int,),  # noqa: E501
            'transactions_per_second': (str,),  # noqa: E501
            'requests_per_second': (str,),  # noqa: E501
            'database_size': (str,),  # noqa: E501
            'full_database_size': (str,),  # noqa: E501
            'text_index_size': (str,),  # noqa: E501
            'online_users': (OnlineUsers,),  # noqa: E501
            'report_calculator_threads': (int,),  # noqa: E501
            'notification_analyzer_threads': (int,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        val = {
        }
        if not val:
            return None
        return {'type': val}

    attribute_map = {
        'installation_folder': 'installationFolder',  # noqa: E501
        'database_location': 'databaseLocation',  # noqa: E501
        'logs_location': 'logsLocation',  # noqa: E501
        'available_processors': 'availableProcessors',  # noqa: E501
        'available_memory': 'availableMemory',  # noqa: E501
        'allocated_memory': 'allocatedMemory',  # noqa: E501
        'used_memory': 'usedMemory',  # noqa: E501
        'uptime': 'uptime',  # noqa: E501
        'started_time': 'startedTime',  # noqa: E501
        'database_background_threads': 'databaseBackgroundThreads',  # noqa: E501
        'pending_async_jobs': 'pendingAsyncJobs',  # noqa: E501
        'cached_results_count_in_db_queries_cache': 'cachedResultsCountInDBQueriesCache',  # noqa: E501
        'database_queries_cache_hit_rate': 'databaseQueriesCacheHitRate',  # noqa: E501
        'blob_strings_cache_hit_rate': 'blobStringsCacheHitRate',  # noqa: E501
        'total_transactions': 'totalTransactions',  # noqa: E501
        'transactions_per_second': 'transactionsPerSecond',  # noqa: E501
        'requests_per_second': 'requestsPerSecond',  # noqa: E501
        'database_size': 'databaseSize',  # noqa: E501
        'full_database_size': 'fullDatabaseSize',  # noqa: E501
        'text_index_size': 'textIndexSize',  # noqa: E501
        'online_users': 'onlineUsers',  # noqa: E501
        'report_calculator_threads': 'reportCalculatorThreads',  # noqa: E501
        'notification_analyzer_threads': 'notificationAnalyzerThreads',  # noqa: E501
        'id': 'id',  # noqa: E501
        'type': '$type',  # noqa: E501
    }

    read_only_vars = {
        'installation_folder',  # noqa: E501
        'database_location',  # noqa: E501
        'logs_location',  # noqa: E501
        'available_processors',  # noqa: E501
        'available_memory',  # noqa: E501
        'allocated_memory',  # noqa: E501
        'used_memory',  # noqa: E501
        'uptime',  # noqa: E501
        'started_time',  # noqa: E501
        'database_background_threads',  # noqa: E501
        'pending_async_jobs',  # noqa: E501
        'cached_results_count_in_db_queries_cache',  # noqa: E501
        'database_queries_cache_hit_rate',  # noqa: E501
        'blob_strings_cache_hit_rate',  # noqa: E501
        'total_transactions',  # noqa: E501
        'transactions_per_second',  # noqa: E501
        'requests_per_second',  # noqa: E501
        'database_size',  # noqa: E501
        'full_database_size',  # noqa: E501
        'text_index_size',  # noqa: E501
        'report_calculator_threads',  # noqa: E501
        'notification_analyzer_threads',  # noqa: E501
        'id',  # noqa: E501
        'type',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Telemetry - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            installation_folder (str): [optional]  # noqa: E501
            database_location (str): [optional]  # noqa: E501
            logs_location (str): [optional]  # noqa: E501
            available_processors (int): [optional]  # noqa: E501
            available_memory (str): [optional]  # noqa: E501
            allocated_memory (str): [optional]  # noqa: E501
            used_memory (str): [optional]  # noqa: E501
            uptime (str): [optional]  # noqa: E501
            started_time (int): [optional]  # noqa: E501
            database_background_threads (int): [optional]  # noqa: E501
            pending_async_jobs (int): [optional]  # noqa: E501
            cached_results_count_in_db_queries_cache (int): [optional]  # noqa: E501
            database_queries_cache_hit_rate (str): [optional]  # noqa: E501
            blob_strings_cache_hit_rate (str): [optional]  # noqa: E501
            total_transactions (int): [optional]  # noqa: E501
            transactions_per_second (str): [optional]  # noqa: E501
            requests_per_second (str): [optional]  # noqa: E501
            database_size (str): [optional]  # noqa: E501
            full_database_size (str): [optional]  # noqa: E501
            text_index_size (str): [optional]  # noqa: E501
            online_users (OnlineUsers): [optional]  # noqa: E501
            report_calculator_threads (int): [optional]  # noqa: E501
            notification_analyzer_threads (int): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Telemetry - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            installation_folder (str): [optional]  # noqa: E501
            database_location (str): [optional]  # noqa: E501
            logs_location (str): [optional]  # noqa: E501
            available_processors (int): [optional]  # noqa: E501
            available_memory (str): [optional]  # noqa: E501
            allocated_memory (str): [optional]  # noqa: E501
            used_memory (str): [optional]  # noqa: E501
            uptime (str): [optional]  # noqa: E501
            started_time (int): [optional]  # noqa: E501
            database_background_threads (int): [optional]  # noqa: E501
            pending_async_jobs (int): [optional]  # noqa: E501
            cached_results_count_in_db_queries_cache (int): [optional]  # noqa: E501
            database_queries_cache_hit_rate (str): [optional]  # noqa: E501
            blob_strings_cache_hit_rate (str): [optional]  # noqa: E501
            total_transactions (int): [optional]  # noqa: E501
            transactions_per_second (str): [optional]  # noqa: E501
            requests_per_second (str): [optional]  # noqa: E501
            database_size (str): [optional]  # noqa: E501
            full_database_size (str): [optional]  # noqa: E501
            text_index_size (str): [optional]  # noqa: E501
            online_users (OnlineUsers): [optional]  # noqa: E501
            report_calculator_threads (int): [optional]  # noqa: E501
            notification_analyzer_threads (int): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            type (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
