# flake8: noqa

"""
    YouTrack REST API

    YouTrack issue tracking and project management system  # noqa: E501

    The version of the OpenAPI document: 2021.3
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from youtrack_api.api_client import ApiClient

# import Configuration
from youtrack_api.configuration import Configuration

# import exceptions
from youtrack_api.exceptions import OpenApiException
from youtrack_api.exceptions import ApiAttributeError
from youtrack_api.exceptions import ApiTypeError
from youtrack_api.exceptions import ApiValueError
from youtrack_api.exceptions import ApiKeyError
from youtrack_api.exceptions import ApiException
